#!/bin/bash

cd $(dirname $0)

mkdir -p /etc/ca-certificates/
cp -f jssecacerts /etc/ca-certificates/
cp -f gatling.p12 /etc/pki/tls/private/
cp -f gatling.cloud.conf ../src/test/resources/gatling.conf

